name: Main

on: [ push ]

jobs:

  build:
    runs-on: ubuntu-22.04
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.300

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build and test
      run: |
        dotnet tool restore
        dotnet build
        dotnet fable ./demo

    - name: Pack
      run: |
        dotnet pack . --output ./nuget

    - name: Publish
      run: |
        dotnet nuget push ./nuget/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
